const string = {
  //Common
  Auth: {
    Login: {
      BackAction1: 'Hold on!',
      BackAction2: 'Are you sure you want to Exit?',
    },
    SignUp: {
      Fname: "fname",
      Lname: "lname",
      Mobile: 'mobile',
      Gender: 'gender',
      Address: 'address',
      City: "city",
      State: "state",
      Country: "country",
      Email: "email",
      Password: "password",
      Mobile_Type: "phone-pad",
      Cpassword: "cpassword",
      CommonType: "email-address",
      GenderMale: 'Male',
      GenderFemale: 'Female',
      Image: "image",
      GenderOther: 'Others',
      currentUserId: "currentUserId",
      User_Added: 'Thank you,please verify your email checkout link in your inbox',
      Email_Exist: 'This email is already exist ,kindly Login',
    },
    Token: 'token',
    Current_User_Id: 'currentUserId',
    Mail_Verified: 'Please Verify your mail or Check out Inbox',
    Invalid_Credential: 'The Credentials are invalid,Kindly check your Credentials',
    Unauthorized: 'The user Is unauthorised',
    Passwordlinksent: 'Password reset link sent successfully',
    Passwordlinknotsent: 'We have sent a password reset link to the specified email address. Please follow the instructions to reset your password.',
  },
  Expense_List: {
    Expense_Done_By: 'by ',
    Expense_Done_in: 'in '
  },
  BackHandler: {
    BackPress: "hardwareBackPress",
    KeyboardScrollTap: "handled",
    KeyboardType: "default",

  },
  PlaceHolder: {
    Search: "Search",
    DropdownTitle: "title",
    Value: '_id',
    Select_Room: "Select Room"
  },
  Commom_Error_Message: {
    EmptyEmail: 'Email is empty',
    Server_Down:
      'Sorry,There is some issue with server side Kindly contact admin',
    Password_Error: 'Please enter a valid password',
    EmailError: 'Please Enter valid Email',
    Server_Error: 'Sorry,There is some server Error',
    Redirect: 'Reached to maximum time limit',
    Title_error: 'Please Enter Valid Title',
    FirstName_Error: 'Please enter valid first name',
    LastName_Error: 'Please enter valid last name',
    Password: 'Please enter password',
    C_Password: 'Please enter valid confirm password',
    Compare_Password_Cpassword:
      'Please check password and confirmpassword are same or not',
    Mobile_Error: 'Please enter valid mobile',
    Address_Error: 'Please enter valid address',
    City_Error: 'Please enter valid city',
    State_Error: 'Please enter valid state',
    Country_Error: 'Please enter valid country',
    Mobile_OnlyNumeric: 'Only numeric values are allowed for mobile',
    Password_Regex_Error:
      'Password must contain one uppercase, one lowercase, one digit and one special character without any space in between and should have a min length of 8 characters  ',
    ProfilePicture_Error: 'Please select Profile Picture',
    Room_error: 'Please Select Room Name',
    Description_error: 'Please Enter Valid Description',
    Amount_error: 'Please enter a valid Amount',
    Amount_onlyNumeric: 'Only numeric values are allowed for Amount',
    Amount_Negative_value_error: 'Only positive values are allowed for amount',
    Expense_Not_Added:
      'Sorry expense has not been added due to some server error',
    Expense_Added: 'Thank you,Your Expense has been Added Successfully',
    Whitespace_title: 'No whitespace and empty field are allowed for title',
    Whitespace_description:
      'No whitespace and empty field are allowed for Description',
    Expense_Update: 'Thank You, Your Expense Has been Updated Successfully',
    Expense_Not_Updated: 'Your Expense Has Not been Updated Successfully',
    User_updated: 'Thank you,your profile data is updated successfully',
    Current_password_error: 'Please enter valid current password',
    New_password_error: 'Please enter valid new password',
    Confirm_password_error: 'Please enter valid connfirm password',
    Password_updated: 'Thank you,Your password is updated',
    Password_not_updated: 'Please enter correct current password',
    Purpose_error: 'Please enter a valid purpose',
    Notification_string1: 'Your Donation of Rs ',
    Notification_success: ' has successfully completed from GatewayPrayash',
    Notification_not_success: ' has not been completed from GatewayPrayash',
    Deleted_Expense: 'Expense Deleted Successfully',
    Not_Deleted_Expense: 'Expense has not been deleted yet',
    Error_searchBar: 'No whitespace and empty field are allowed for Searchbar',
    Logout: 'Thank you,Logout successfully',
    Alert_Logout1: 'Logout',
    Alert_Logout2: 'Are you sure you want to log out?',
    Room_Name_Text: 'Room Name',
    Description_Text: 'Description',
    Amount_Text: 'Amount',
    Title_Text: 'Title',
    Purpose_Text: 'Purpose',
    Edit_Expense_Text: 'Edit Expense Title',
    RoomName_Text: 'RoomName',
    Alert_Delete: 'DELETE',
    Alert_Delete2: 'Are you sure you want to delete this expense?',
    Empty_Room_Err:
      ' As eager we are to have you join a room, we cant seem to find the perfect one for you. Please try again in sometime.',
    Empty_Search_Err: 'No search results',
    Alert_Err_Exit1: 'Hold on!',
    Alert_Err_Exit2: 'Are you sure you want to Exit?',
    Data_Not_Found_Text: 'Data Not Found',
    Logout_message: "Do you want to logout ?",
    Delete_Message:"Do yo want to Delete ?"
  },
  Common: {
    Ruppee: '\u20B9',
    Date_Format: 'DD/MM/YYYY',
    Date_Format2: "lll",
    Gateway_url: 'https://thegatewaycorp.com/',
    Focus: "focus",
    Numeric: "numeric",
    ThankYou: "Thank You",
    Sorry: "Sorry",
    None: "none",
    Contains: "contain",
    Fade: "fade",
    Top: "top"
  },
  Navigations: {
    Login: "Login",
    Registration: "registration",
    BottomNavigation: "bottomNavigation",
    Home: "home",
    ForgetPassword: "ForgetPassword",
    RoomDetails: "RoomDetail",
    Expense_Room: "Expenserroom",
    DonationRoomList: "Droomlist",
    MemberList: "MemberList",
    Auth: 'Auth',
    Payment_History: 'PaymentHistory',
    Change_Password: 'changePassword',
    User_Expenselist: 'UserExpenseList',
    Account: 'more',
    ExpenseList: "ExpenseList",
    Splash: 'SplashScreen',
    Add_Expense: 'Expense',
    Expense_List: 'ExpenseList',
    Donate: 'donate',
    EditProfile: 'editprofile',
    History: 'history',
    EditExpense: 'EditExpense',
    Payment: 'Payment',
    RoomDetail: 'RoomDetail',
    ExpenseRoom: 'Expenserroom',
    Donation_List: "Dlist",
  },
  Icons_Name: {
    Mail_Icon: 'mail',
    Eye_Lock: 'lock',
    Eye_Slash: 'eye-slash',
    Eye: 'eye',
    Eye_off_outline: 'eye-off-outline',
    Eye_outline: 'eye-outline',
    Account_Balance_Wallet: 'account-balance-wallet',
    Mail_Outline: 'email-outline',
    Phone_Outline: 'phone-outline',
    Heart_Outline: 'heart-outline',
    Credit_Card_Outline: 'credit-card-outline',
    Key_Outline: 'key-outline',
    Account_Check_Outline: 'account-check-outline',
    Logout_Outline: "logout-variant",
    Person_Filled: "person",
    Email_Filled: "email",
    Description_Filled: "description",
    Import_Contact_Filled: "import-contacts",
    Icon: "logo",
    EditProfile_Outline: 'account-edit-outline',
  },
  Icons_Size: {
    Twenty: 20,
    Zero: 0,
    Eight: 8,
    Ten: 10,
    TwentyFive: 25,
    Two: 2,
    TwentyTwo: 22,
    One: 1,
    Threeh: 300,
    Oneh: 100,
    NegativeOne: -1,
    NegativeFifty:-50,
    Eighty: 80,
    Five: 5,
    Twofiveh: 250,
    Eighteen:18,
    ThirtyFive: 35,
    SixtyFive: 65
  },
  Regex: {
    Email_Regex:/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w\w+)+$/,
    Password_Regex: /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$/
  },
  Text: {
    Forgot_Password_Text: 'Forgot Password',
    Forgot_Password_Instructions:
      'Please enter your email address.You will receive a link to create a new password via email',
    Email_Text: 'Email',
    Password_Text: 'Password',
    SignUpText: 'Sign Up',
    Registration_Text: 'Registration',
    Tell_Your_Friends_Text: 'Tell Your Friends',
    First_name_Text: 'First Name',
    Last_name_Text: 'Last Name',
    RoomDetail: 'Room Details',
    Mobile_Text: 'Mobile',
    Gender_Text: 'Gender',
    Address_Text: 'Address',
    City_Text: 'City',
    Loading_Text: 'Loading...',
    State_Text: 'State',
    Country_Text: 'Country',
    Confirm_Password_Text: 'Confirm Password',
    Data_Not_Available_Text: 'Data Not Available',
    Statusbar_Style: 'light-content',
    Total_Amount_Text: 'Total Amount',
    Total_Expense_Text: 'Total Expense',
    Zero_Text: 0,
    Expense_List_Text: 'Expense List',
    Donation_List_Text: 'Donation List',
    Member_List_Text: 'Members List',
    Balance_Text: 'Balance',
    Members_Text: 'Members',
    Donation_Text: 'Donation',
    Expense_Text: 'Expense',
    Current_Pass_Text: 'Current Password',
    New_Pass_Text: 'New Password',
    Donate_History_Text: 'My Donate History',
    ChangePassword_Text: 'Change Password',
    Confirm_Pass_Text: 'Confirm Password',
    Total_Donation_Text: 'Total Donation',
    Share_Text: 'Hello, From the Gateway',
    Android_Text: 'android',
    Gateway_Group_Text: 'Gateway Group',
    Logout: 'Logout',
    History_Text: 'History',
    EditProfile_Text: 'Edit Profile',
    Profile_Text: 'Profile',
    Donate_Text: 'Donate',
    RoomList_Text: 'RoomList',
    Add_Expense_Text: 'Add Expense',
    Edit_Expense_Text: 'Edit Expense',
    MemberList_Text: 'Member List',
    Room_Expense_List: 'Room Expense List',
    Room_Donation_List: 'Room Donation List',
    My_Expense_List_Text: 'My Expense List',
    Top_Text:'top',
    Wrong_Toast:"Something went wrong!",
    Slidein:'slide-in',
    Google_Map_Api_Key:'AIzaSyAXVdAtjEIheDNNgHa-DFtjD_YgEtww7vg',
  },
  Returntype: {
    Done: "done",
    Next: "next",
  },
  Buttons: {
    BtnRegister: "Register",
    BtnLogin: 'Login',
    Btnsend: 'Send',
    BtnClear: 'clear',
    BtnAdd: 'Add',
    BtnUpdate: "Update",
    BtnCancel: 'Cancel',
    BtnReset: 'Reset',
    BtnDelete: 'Delete',
    Btnok: 'OK',
    BtnDonate: 'Donate',
    BtnYes: "YES",
    BtnExit:"Exit"
  },
  Toastcode: {
    Success: "success",
    Warning: "warning",
    Danger: 'danger'
  },
  Notification: {
    Channel_Id: "channel-id",
    Channel_Id2: "channel-id2",
    Notify_Description: "A channel to categorise your notifications",
    Sound_Name: "default",
    ChannelName1: "My channel",
    ChannelName2: "My channel1"
  },
  Size:{
    Fontweight:{
      Bold:"bold",
      SevenHundered:"700",
      FourHundred:"400",
      FiveHundred: '500',
      SixHundred: '600',
    },
    One:1,
    Eighteen:18,
    Six:6,
    Four:4,
    FiftyFive:55,
    ZeroPointThree:0.3,
    ZeroPointOne:0.1,
    ZeroPointTwo:0.2,
    SixtyNine:69,
    ZeroPointFive:0.5,
    ZeroPointEight:0.8,
    FiveHundred:500,
    Ten:10,
    Fifteen:15,
    Sixteen:16,
    SeventyOne:71,
    Seventy:70,
    Eighty:80,
    Twenty:20,
    Thirteen:13,
    TwentyOne:21,
    Five:5,
    Twelve:12,
    TwentyFive:25,
    ThreeHundred:300,
    Two:2,
    Forty:40,
    OneTwenty:120,
    Eight:8,
    ThirtyFour:34,
    ThirtyFive:35,
    ThirtyEight:38,
    TwentyFour:24,
    NegativeThirty:-30,
    FortySix:46,
    FortyFive:45,
    Fifty:50,
    Thirty:30,
    Hundred:100,
    Fourteen:14,
    Sixty:60,
    Nine:9,
    TwoHundred:200,
    TwoThousand:2000,
    Three: 3,
    Seven: 7,
    Eleven: 11,
    FiftyTwo: 52,
    TwentyTwo: 22,
    TwentyThree: 23,
    FortyEight: 48,
    FiftySix: 56,
    NinetyFive: 95,
    Ninety: 90,
    OneTwentyFive: 125,
    OneFiftyFour: 154,
    TwoFifty: 250,
    TwoTwenty: 220,
    TwoThirty:230,
    SixNinety: 690,
  },
  Percent:{
    Seventyone:'71%',
    Hundred:"100%",
    Fifty:"50%",
    Ten:"10%",
    Ninty:"90%",
    Thirteen:"13%",
    FortyFive:"45%",
    EightyEight:"88%",
    Twenty:"20%",
    Eighty:"80%",
    TwentyFive:"25%",
    Sixty:"60%",
    NinetyFour:"94%",
    TwentySix:"26%",
    Fifteen:"15%",
    Forty:"40%",
    Four: '4%',
    Thirty:"30%",
    Six:"6%",
    NinetyOne: '91%',
    NinetyThree: '93%',
    EightyNine: '89%',
    EightyThree: '83%',
    FiftyFive:"55%",
    NinetyEight: '98%',
    NinetyFive: '95%',
    SixtyThree: '63%',
    NinetySix: '96%',
    FortyNine: '49%',
    TwentyEight: '28%',
    Seventy:"70%",
    NintySeven:"97%",
    EightAndHalf:'8.5%',
    NintyFive:"95%",
    Two:'2%'
  },
  Styles:{
    Row:'row',
    Center:"center",
    Solid:'solid',
    Normal:"normal",
    Flex:'flex',
    Absolute:'absolute',
    Justify:'justify',
    Left:"left",
    None:'none',
    Bold: 'bold',
    FlexEnd: 'flex-end',
    FlexStart: 'flex-start',
    Underline: 'underline',
    SpaceBetween: 'space-between',
    Roboto:'Roboto',
    Right:"right"
  },
  Token:{
    apiToken :"Basic Z25uLWFwaS11c2VyOkZLbjVyN1JjYUtJI2tTcTJvKUByQF4jMg=="
  }
};
export default string;
